import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // 공통으로 쓰는 css
import styles from "@/app/page.module.css"; // 개별로 쓰는 css
import MSWComponent from "./_component/MSWComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 페이지를 넘나드는데도 안바뀌는 루트 레이아웃(최상위 레이아웃)
// page가 {children}안에 있다고 생각
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        {children}
      </body>
    </html>
  );
}
