import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 페이지를 넘나드는데도 안바뀌는 루트 레이아웃(최상위 레이아웃)
// page가 {children}안에 있다고 생각
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div></div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
